This notebook demonstrates how use the model api to run predictions and get information from the model. You can use it as basis to write your own experiements using the model in this container.

To start, import _modelapi.model_, which will give us access to the api of the model in this container.

In [1]:
import matplotlib.pyplot as plt
import h5py
from modelapi import model

Initiating U-Net
Initiating U-Net no padding


In [ ]:
result = model.predict('sample_data/sample.json')
result

loading done
affine recovered
Sanity check on boxed data:
Element has shape (136, 172, 134)
Element has shape (136, 172, 134)
Element has shape (136, 172, 134)
Element has shape (136, 172, 134)
Element has shape (136, 172, 134)
Element has shape (136, 172, 134)
dataset assembled
first U-Net running
(240, 240, 155)
[49, 185, 42, 214, 4, 138]
[0, 0, 0, 0, 0, 0]
[[ -1.  -0.  -0.   0.]
 [ -0.  -1.  -0. 239.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]
(5, 136, 176, 136)
torch.Size([1, 5, 136, 176, 136])
prediction1 is running
reshaping predictions
preprocessing step 2
in loop now
reshaping prediction
iterating through regions
second U-Net running
Processing Segmentation...


In [ ]:
# recover prediction from h5 file
resultFile = result["output"][0]["prediction"].replace("api", "")
f = h5py.File(resultFile, 'r')
print(list(f.keys()))
# load the actual prediction and check for correct shape
prediction = f["Segmentation"]
print('Shape of prediction is: {}'.format(prediction.shape))

In [ ]:
plt.imshow(prediction[90], aspect=0.5)
print(prediction[90].max(), prediction[90].min())

Ask the model for a list of sample data, then run a prediction on the first of the sample dataset, and then display the prediction result output.

If the model does not provide any sample data, print an error message (this part also shows how to read meta info - like the model's name - from the models config).

In [ ]:
samples = model.get_samples()
if len(samples["files"]) > 0:
    inputFile = samples["folder"] + "/" + samples["files"][0]
    result = model.predict(inputFile)
    for i, output in enumerate(result["output"]):
        print("\n" + result["model"]["name"] + " Output " + str(i) + ":")
        print("  Type:  " + output["type"])
        print("  Name:  " + output["name"])
        print("  Shape: " + str(output["shape"]))
        print("  Prediction:")
        if output["type"] in ["mask_image", "image"]:
            # if output seems to be an image, try displaying it nicely with PIL
            try:
                import PIL
                image = PIL.Image.fromarray(output["prediction"])
                display(image)
            except:
                display(output["prediction"])
        else:
            display(output["prediction"])
else:
    model_name = model.get_config()["meta"]["name"]
    print(model_name + " does not provide any sample data, please try your own data.")